### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by zcs8** [univeous/koishi-plugin-emojimix#7]
以下是运行日志：
emojimix Error: connect ECONNREFUSED 0.0.0.0:443
                            at createConnectionError (node:net:1647:14)
                            at afterConnectMultiple (node:net:1677:16)
2024-10-07 18:59:15 [W] emojimix Error: connect ECONNREFUSED :::443
                            at createConnectionError (node:net:1647:14)
                            at afterConnectMultiple (node:net:1677:16)

2024-10-07 18:59:15 [W] emojimix TypeError: fetch failed
                            at node:internal/deps/undici/undici:13185:13
                            at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
                            at async [cordis.invoke] (/data/data/com.termux/files/home/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
                            at async Proxy.<anonymous> (/data/data/com.termux/files/home/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:178:26)

2024-10-07 18:59:15 [W] emojimix Error: fetch https://github.com/univeous/koishi-plugin-emojimix/raw/master/data.json failed
                            at /data/data/com.termux/files/home/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:320:23
                            at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
                            at async [cordis.invoke] (/data/data/com.termux/files/home/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
                            at async Proxy.<anonymous> (/data/data/com.termux/files/home/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:178:26)
请问如何解决？

**Comment by univeous** [comment]
网络问题，挂代理
或者配置里改成`https://testingcf.jsdelivr.net/gh/univeous/koishi-plugin-emojimix@master/data.json`试试

**Comment by zcs8** [comment]
感谢，目前已解决该问题
